### ISSUE TITLE
Make 4th fully customizable dialog

### ISSUE THREAD

**Issue by dvorapa** [dvorapa/dialog-dart#13]
``` Dart
dynamic/void dialog({content,header,buttons,whatToReturn,backdrop,styles,...})
```

**Comment by Google-Cat** [comment]
Thanks a lot for your library, but can you demonstrate, how can I transform sample html file to List<? extends Node> (example). I know, that I can manually do like this: `[new Dialog([new HtmlElement(),new FileUploadInputElement()]` But I don't want to do so.

**Comment by dvorapa** [comment]
Try to [search Dart docs](https://api.dartlang.org/stable/1.17.1/dart-html/dart-html-library.html) ;-) I'm sure there is some built-in method to make html file into list of nodes, just don't have time to find it. Btw I think the list of nodes is the default for appending in dart:html.

**Comment by dvorapa** [comment]
> Thanks a lot for your library, but can you demonstrate, how can I transform sample html file to List<? extends Node> (example). I know, that I can manually do like this: `[new Dialog([new HtmlElement(),new FileUploadInputElement()]` But I don't want to do so.

See e.g. https://stackoverflow.com/questions/19467115/in-dart-parse-html-string-to-dom
