### ISSUE TITLE
NoSuchMethodError using alert

### ISSUE THREAD

**Issue by mbenatti** [dvorapa/dialog-dart#7]
NoSuchMethodError: method not found: 'DialogElement'
Receiver: Type: class 'DialogElement'
Arguments: [...](package:dialog/src/dialog_class.dart:11)

Code:

import 'dart:html';
import 'package:dialog/dialog.dart';

void main() {
  querySelector("#sample_text_id")
      ..text = "Click me!"
      ..onClick.listen(reverseText);
}

void reverseText(MouseEvent event) {
  alert("teste");
}

**Comment by dvorapa** [comment]
Should be fully resolved in the new release https://github.com/dvorapa/dialog-dart/releases/tag/v0.4.0
